# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07e338da5ed64c145b16a79170c5774a5854116e77d46e5432847a6533959631d4224d953efde0dea40daa1d8af441cf2d4284c08a35ce1c4231cd37350dc9ca

test:
  secret_key_base: 659320c9c74e7a3603ea7f4abfa190d265ed9d1a5d400d974074d35efd62d32b6be4a7dc6960810b07c5553b9377b25a3ec3dbf848e7a5d1926e79c164745add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
